name:          "WTF, HTML 그리고 CSS?"
url:           http://snack-x.github.io/wtf-html-css
repo:          https://github.com/snack-x/wtf-html-css
twitter:       https://twitter.com/mdo
twitter_snack: https://twitter.com/Snack_X

markdown:      redcarpet
permalink:     pretty
pygments:      true
